import { db } from '../firebase/config';
import { collection, doc, writeBatch, Timestamp } from 'firebase/firestore';
import type { Category, Product } from '../types';

export const DEMO_CATEGORIES: Partial<Category>[] = [
  {
    id: 'cat-ranks',
    name: 'Ranks',
    slug: 'ranks',
    description: 'Lifetime VIP, MVP, and Elite ranks with game-changing perks and cosmetics.',
    icon: 'Shield',
    iconUrl: '',
    bannerUrl: '',
    color: '#8b5cf6',
    enabled: true,
    sortOrder: 1,
    announcementEnabled: false,
    announcementTitle: '',
    announcementMessage: '',
    announcementIcon: '',
    announcementColor: '',
    announcementButtonText: '',
    announcementButtonUrl: '',
  },
  {
    id: 'cat-keys',
    name: 'Crate Keys',
    slug: 'crate-keys',
    description: 'Open mystical crates in-game to unbox rare weapons, armor, and multipliers.',
    icon: 'Key',
    iconUrl: '',
    bannerUrl: '',
    color: '#f59e0b',
    enabled: true,
    sortOrder: 2,
    announcementEnabled: false,
    announcementTitle: '',
    announcementMessage: '',
    announcementIcon: '',
    announcementColor: '',
    announcementButtonText: '',
    announcementButtonUrl: '',
  },
  {
    id: 'cat-bundles',
    name: 'Bundles',
    slug: 'bundles',
    description: 'Save big with all-in-one value packs containing ranks, keys, and cosmetics.',
    icon: 'Gift',
    iconUrl: '',
    bannerUrl: '',
    color: '#ec4899',
    enabled: true,
    sortOrder: 3,
    announcementEnabled: false,
    announcementTitle: '',
    announcementMessage: '',
    announcementIcon: '',
    announcementColor: '',
    announcementButtonText: '',
    announcementButtonUrl: '',
  },
  {
    id: 'cat-kits',
    name: 'Kits',
    slug: 'kits',
    description: 'Claim gear, weapons, and supply packs right after respawning.',
    icon: 'Layers',
    iconUrl: '',
    bannerUrl: '',
    color: '#10b981',
    enabled: true,
    sortOrder: 4,
    announcementEnabled: false,
    announcementTitle: '',
    announcementMessage: '',
    announcementIcon: '',
    announcementColor: '',
    announcementButtonText: '',
    announcementButtonUrl: '',
  },
  {
    id: 'cat-coins',
    name: 'Coins',
    slug: 'coins',
    description: 'In-game economy currency for trading, auction house, and shop upgrades.',
    icon: 'Coins',
    iconUrl: '',
    bannerUrl: '',
    color: '#eab308',
    enabled: true,
    sortOrder: 5,
    announcementEnabled: false,
    announcementTitle: '',
    announcementMessage: '',
    announcementIcon: '',
    announcementColor: '',
    announcementButtonText: '',
    announcementButtonUrl: '',
  },
];

export const DEMO_PRODUCTS: Partial<Product>[] = [
  {
    id: 'prod-vip',
    name: 'VIP Rank',
    slug: 'vip-rank',
    categoryId: 'cat-ranks',
    categoryName: 'Ranks',
    shortDescription: 'The essential starter rank with lobby flight, chat color, and daily rewards.',
    fullDescription:
      'VIP is the perfect entry rank for NightmareMC players. Unlock permanent lobby flight, exclusive green chat prefix, 3 extra home locations, and a daily bonus key crate.',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    iconUrl: '',
    bannerUrl: '',
    prices: {
      INR: 299,
      USD: 3.99,
      PKR: 1100,
      BDT: 450,
      NPR: 530,
      AED: 15,
      EUR: 3.50,
      GBP: 3.00,
    },
    badge: 'POPULAR',
    badgeColor: '#8b5cf6',
    features: [
      { id: 'f1', text: 'Permanent VIP Prefix in Chat & Tab', enabled: true },
      { id: 'f2', text: 'Lobby Flight Enabled (/fly)', enabled: true },
      { id: 'f3', text: 'Set up to 5 Player Homes (/sethome)', enabled: true },
      { id: 'f4', text: 'Exclusive VIP Discord Role', enabled: true },
      { id: 'f5', text: 'Priority Server Queue Access', enabled: true },
    ],
    enabled: true,
    featured: true,
    popular: true,
    isNew: false,
    onSale: false,
    limited: false,
    comingSoon: false,
    stockStatus: 'unlimited',
    quantityEnabled: false,
    minQuantity: 1,
    maxQuantity: 1,
    availableQuantities: [1],
    sortOrder: 1,
    isBundle: false,
    bundleItems: [],
    originalValue: { INR: 399, USD: 4.99 },
    kitContents: [],
    seoTitle: 'VIP Rank — NightmareMC Store',
    seoDescription: 'Buy VIP Rank for NightmareMC Minecraft Server',
  },
  {
    id: 'prod-mvp',
    name: 'MVP Rank',
    slug: 'mvp-rank',
    categoryId: 'cat-ranks',
    categoryName: 'Ranks',
    shortDescription: 'Advanced rank with custom particle trail, 10 homes, and 2x Coin booster.',
    fullDescription:
      'Step up your status with MVP Rank! Enjoy custom purple nametag, glowing cosmetics, 10 home teleport points, auto-sell chest access, and a permanent 1.5x coin multiplier across all gamemodes.',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop',
    iconUrl: '',
    bannerUrl: '',
    prices: {
      INR: 699,
      USD: 8.99,
      PKR: 2500,
      BDT: 1050,
      NPR: 1250,
      AED: 35,
      EUR: 7.99,
      GBP: 6.99,
    },
    badge: 'BEST VALUE',
    badgeColor: '#ec4899',
    features: [
      { id: 'f1', text: 'All VIP perks included', enabled: true },
      { id: 'f2', text: 'Custom MVP Purple Prefix & Particle Glow', enabled: true },
      { id: 'f3', text: '10 Set Homes & /back teleport command', enabled: true },
      { id: 'f4', text: 'Permanent 1.5x Coin Booster', enabled: true },
      { id: 'f5', text: 'Weekly Legendary Crate Key drop', enabled: true },
      { id: 'f6', text: 'Access to Private /vault storage', enabled: true },
    ],
    enabled: true,
    featured: true,
    popular: true,
    isNew: false,
    onSale: true,
    limited: false,
    comingSoon: false,
    stockStatus: 'unlimited',
    quantityEnabled: false,
    minQuantity: 1,
    maxQuantity: 1,
    availableQuantities: [1],
    sortOrder: 2,
    isBundle: false,
    bundleItems: [],
    originalValue: { INR: 899, USD: 11.99 },
    kitContents: [],
    seoTitle: 'MVP Rank — NightmareMC Store',
    seoDescription: 'Buy MVP Rank for NightmareMC Minecraft Server',
  },
  {
    id: 'prod-legkey',
    name: 'Legendary Key',
    slug: 'legendary-key',
    categoryId: 'cat-keys',
    categoryName: 'Crate Keys',
    shortDescription: 'Unlocks the Legendary Crate at spawn with guaranteed top-tier loot.',
    fullDescription:
      'The Legendary Key unlocks the mystical spawn chest. Potential rewards include Enchanted Netherite gear, custom talisman relics, spawner eggs, and millions of server coins.',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    iconUrl: '',
    bannerUrl: '',
    prices: {
      INR: 99,
      USD: 1.29,
      PKR: 350,
      BDT: 150,
      NPR: 180,
      AED: 5,
      EUR: 1.19,
      GBP: 0.99,
    },
    badge: 'HOT',
    badgeColor: '#f59e0b',
    features: [
      { id: 'f1', text: 'Guaranteed Rare or Epic Drop', enabled: true },
      { id: 'f2', text: 'Chance at Full Netherite Armor Kit', enabled: true },
      { id: 'f3', text: 'Instant In-Game Delivery upon staff confirmation', enabled: true },
      { id: 'f4', text: 'Never Expires', enabled: true },
    ],
    enabled: true,
    featured: true,
    popular: false,
    isNew: true,
    onSale: false,
    limited: false,
    comingSoon: false,
    stockStatus: 'unlimited',
    quantityEnabled: true,
    minQuantity: 1,
    maxQuantity: 20,
    availableQuantities: [1, 3, 5, 10],
    sortOrder: 3,
    isBundle: false,
    bundleItems: [],
    originalValue: { INR: 120, USD: 1.50 },
    kitContents: [],
    seoTitle: 'Legendary Key — NightmareMC Store',
    seoDescription: 'Buy Legendary Keys for NightmareMC Minecraft Server',
  },
  {
    id: 'prod-starter-bundle',
    name: 'Nightmare Starter Bundle',
    slug: 'nightmare-starter-bundle',
    categoryId: 'cat-bundles',
    categoryName: 'Bundles',
    shortDescription: 'VIP Rank + 3× Legendary Keys + Starter Kit at 35% discount.',
    fullDescription:
      'The ultimate kickstart pack for any player entering NightmareMC. Get instant VIP status, 3 Legendary crate keys, and the full diamond starter survival kit at our steepest discount.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    iconUrl: '',
    bannerUrl: '',
    prices: {
      INR: 499,
      USD: 6.49,
      PKR: 1800,
      BDT: 750,
      NPR: 900,
      AED: 25,
      EUR: 5.99,
      GBP: 4.99,
    },
    badge: '35% OFF',
    badgeColor: '#ef4444',
    features: [
      { id: 'f1', text: 'Includes VIP Rank (Lifetime)', enabled: true },
      { id: 'f2', text: '3× Legendary Crate Keys', enabled: true },
      { id: 'f3', text: 'Starter Survival Kit (Diamond Gear)', enabled: true },
      { id: 'f4', text: '50,000 In-Game Coins', enabled: true },
    ],
    enabled: true,
    featured: true,
    popular: true,
    isNew: true,
    onSale: true,
    limited: false,
    comingSoon: false,
    stockStatus: 'unlimited',
    quantityEnabled: false,
    minQuantity: 1,
    maxQuantity: 1,
    availableQuantities: [1],
    sortOrder: 4,
    isBundle: true,
    bundleItems: [
      { productId: 'prod-vip', productName: 'VIP Rank', quantity: 1 },
      { productId: 'prod-legkey', productName: 'Legendary Key', quantity: 3 },
      { productId: 'prod-startkit', productName: 'Starter Kit', quantity: 1 },
    ],
    originalValue: { INR: 799, USD: 9.99 },
    kitContents: [],
    seoTitle: 'Nightmare Starter Bundle — NightmareMC Store',
    seoDescription: 'Save 35% on the Nightmare Starter Bundle',
  },
  {
    id: 'prod-startkit',
    name: 'Starter Kit',
    slug: 'starter-kit',
    categoryId: 'cat-kits',
    categoryName: 'Kits',
    shortDescription: 'Full diamond tools, armor, and 64 golden apples.',
    fullDescription:
      'Jump straight into the action without tedious resource gathering. Spawns with Protection IV Diamond Armor, Sharpness V Diamond Sword, Efficiency V Pickaxe, and food rations.',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    iconUrl: '',
    bannerUrl: '',
    prices: {
      INR: 149,
      USD: 1.99,
      PKR: 550,
      BDT: 230,
      NPR: 270,
      AED: 8,
      EUR: 1.79,
      GBP: 1.49,
    },
    badge: 'KIT',
    badgeColor: '#10b981',
    features: [
      { id: 'f1', text: 'Protection IV Diamond Armor Set', enabled: true },
      { id: 'f2', text: 'Sharpness V, Unbreaking III Diamond Sword', enabled: true },
      { id: 'f3', text: 'Efficiency V, Fortune III Diamond Pickaxe', enabled: true },
      { id: 'f4', text: '64× Golden Apples & 32× Ender Pearls', enabled: true },
    ],
    enabled: true,
    featured: false,
    popular: false,
    isNew: false,
    onSale: false,
    limited: false,
    comingSoon: false,
    stockStatus: 'unlimited',
    quantityEnabled: true,
    minQuantity: 1,
    maxQuantity: 5,
    availableQuantities: [1, 2, 3, 5],
    sortOrder: 5,
    isBundle: false,
    bundleItems: [],
    originalValue: { INR: 199, USD: 2.50 },
    kitContents: [
      'Diamond Helmet (Prot IV, Unbr III)',
      'Diamond Chestplate (Prot IV, Unbr III)',
      'Diamond Leggings (Prot IV, Unbr III)',
      'Diamond Boots (Prot IV, Feather Fall IV)',
      'Diamond Sword (Sharp V, Fire II)',
      'Diamond Pickaxe (Eff V, Fortune III)',
      '64x Golden Apples',
      '32x Ender Pearls',
    ],
    kitPreviewImageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    ],
    seoTitle: 'Starter Kit — NightmareMC Store',
    seoDescription: 'Buy Starter Kit for NightmareMC Minecraft Server',
  },
];

export async function seedDemoData() {
  const batch = writeBatch(db);

  DEMO_CATEGORIES.forEach(cat => {
    const docRef = doc(collection(db, 'categories'), cat.id!);
    batch.set(docRef, { ...cat, createdAt: Timestamp.now(), updatedAt: Timestamp.now() });
  });

  DEMO_PRODUCTS.forEach(prod => {
    const docRef = doc(collection(db, 'products'), prod.id!);
    batch.set(docRef, { ...prod, createdAt: Timestamp.now(), updatedAt: Timestamp.now() });
  });

  await batch.commit();
}
